###########################  
# In this example:
# - 2 filebeat send application log to lagtash with field "application: nginx-access-log" & "application: nginx-1-access-log"
# - Log will storage in 2 index format with timestamp "YYYY.MM.dd"
#   + "application: nginx-access-log" => Index "nginx-%{+YYYY.MM.dd}"
#   + "application: nginx-1-access-log" => Index "nginx-1-%{+YYYY.MM.dd}"
########################### 

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [fields][application] == "nginx-access-log" or  [fields][application] == "nginx-error-log" {
        mutate {
          add_field => { "log_type" => "nginx" }
        }

        grok {
          match => { "message" => "%{COMBINEDAPACHELOG}" }
        }
      }
      if [fields][application] == "nginx-1-access-log" or  [fields][application] == "nginx-1-error-log" {
        mutate {
          add_field => { "log_type" => "nginx-1" }
        }

        grok {
          match => { "message" => "%{COMBINEDAPACHELOG}" }
        }
      }

      geoip {
        source => "[source][address]"
        target => "[source]"
      }

    }

    output {
      ## MULTI LOG_TYPE IN MULTI INDEX
      if [log_type] == "nginx" {
        elasticsearch {
          #template_api => legacy
          hosts => ["http://elasticsearch:9200"]
          index => "nginx-%{+YYYY.MM.dd}"
        }
      }
      if [log_type] == "nginx-1" {
        elasticsearch {
          #template_api => legacy
          hosts => ["http://elasticsearch:9200"]
          index => "nginx-1-%{+YYYY.MM.dd}"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.10.0
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: logstash
spec:
  ports:
  - port: 5044
    protocol: TCP
    targetPort: 5044
    name: allow-tcp
  - port: 5044
    protocol: UDP
    targetPort: 5044
    name: allow-udp
  selector:
    app: logstash
status:
  loadBalancer: {}