apiVersion: v1
data:
  auth: a2liYW5hOiRhcHIxJDJFN3N4ZVJvJGJ4VUFSZGxVU1k0aWdEZXNqN003bjEK
kind: Secret
metadata:
  name: kibana-basic-auth
  # namespace: logging
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  # namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.25
        env:
        - name: SERVER_NAME
          value: "kibana.example.com"
        - name: ELASTICSEARCH_HOSTS
          value: '["http://elasticsearch:9200"]'
        - name: SERVER_PUBLICBASEURL
          value: "http://kibana.example.com"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  # namespace: logging
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  # namespace: logging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: kibana-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - kibana'
spec:
  rules:
  - host: kibana.example.com
    http:
      paths:
      - backend:
          service:
            name: kibana
            port:
              number: 5601
        path: /
        pathType: Prefix
status:
  loadBalancer: {}